name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used?

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Scanner
        - New Reporter/Output Format
        - CLI Enhancement
        - Detection Pattern
        - Compliance/Risk
        - Performance
        - Documentation
        - Other
